### ISSUE TITLE
The schedule.png looks very large

### ISSUE THREAD

**Issue by ericearl** [bids-standard/202404-seattle-maintainer-meeting#6]
How do we downsize it by width or height? HTML tags?

**Comment by arokem** [comment]
Resolved in https://github.com/bids-standard/202404-seattle-maintainer-meeting/commit/5fb5d3473b45bb1f0d6e5f6b22744b37e4190e36

**Comment by christinerogers** [comment]
you can also say "width=90%" in the `<img>` tag header so it spans/scales automatically @ericearl

**Comment by arokem** [comment]
Thanks @christinerogers ! Done in https://github.com/bids-standard/202404-seattle-maintainer-meeting/commit/b596a48be31c5f64623a6f7c275c750fd2c405ff
